### ISSUE TITLE
Fails to match some classes with escaped characters

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-match-helper#10]
```js
test("Matcher with class name containing escaped characters", t => {
	const actual = match(".sm\:hidden");
	const expected = { attrs: { class: /(?:^|\s)sm:hidden(?:\s|$)/ } };
	t.deepEqual(actual, expected); // pass

	const actual2 = match(".\[display:none\]");
	const expected2 = { attrs: { class: /(?:^|\s)\[display:none\](?:\s|$)/ } };
	t.deepEqual(actual2, expected2); // fail
});
```

Diff for the failing test:

```diff
- Actual
+ Expected

{
-   tag: '.[display:none]',
+   attrs: {
+     class: /(?:^|\s)\[display:none\](?:\s|$)/,
+   },
}
```

Ran into this while building [posthtml-css-inline](https://github.com/cossssmin/posthtml-css-inline) and trying it out with Tailwind CSS arbitrary class names, such as `[-webkit-font-smoothing:antialiased]`.

**Comment by phloe** [comment]
Yeah - I never thought anyone would be silly enough to use `[]` in classnames 😅

But it's a legit usecase - so I've made a fix.

I think as JS strings the CSS selectors need to be double escaped: `".\[display:none\]"` -> ".\\[display:none\\]"

Try this:

`posthtml-match-helper@1.0.4-dev.0`

**Comment by phloe** [comment]
@cossssmin it's available now.
