### ISSUE TITLE
New release (ESM)

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-match-helper#11]
Hi @phloe, as part of an effort to update and normalize PostHTML libraries to ESM I'd like to work on a major version of `posthtml-match-helper`: 

- [x] ESM-only
- [x] require Node.js 18
- [x] use Vitest and eslint
- [x] add [np](https://www.npmjs.com/package/np) for releases

Please let me know if you're OK with this and I'll get started on the PR right away. Thanks!

**Comment by phloe** [comment]
Cool by me :)

**Comment by cossssmin** [comment]
Awesome, thanks! Btw I think you'll need to add me to the NPM collaborators list, so I can publish the release 👍

**Comment by cossssmin** [comment]
Didn't receive any invite email 🫣

**Comment by phloe** [comment]
You're on the collaborator list 🤔

<img width="795" alt="Screenshot 2024-02-27 at 14 10 18" src="https://github.com/posthtml/posthtml-match-helper/assets/13237/589507d1-f774-42cf-a55f-9a77d3a50628">

Maybe you don't get an email bc you're already part of the posthtml group? I dunno..

**Comment by cossssmin** [comment]
Ah no, I meant on NPM, right now I think you're the only one who has publish rights:

<img alt="image" src="https://github.com/posthtml/posthtml-match-helper/assets/1656595/fb657c62-d3f4-4da1-809a-4e8317692e20">

**Comment by phloe** [comment]
I should try reading what you write... 😅

Invited.

**Comment by cossssmin** [comment]
Accepted, thanks! :)

**Comment by cossssmin** [comment]
Question: do you still want your email listed in `package.json`, or can I do this change:

```diff
- "author": {
- 	"name": "phloe",
- 	"email": "mail@phloe.industries"
- },
+ "author": "Rasmus Fløe (https://github.com/phloe)",
```

**Comment by phloe** [comment]
Without email is good :)

**Comment by phloe** [comment]
Looks good from here - Approved!

**Comment by cossssmin** [comment]
Done, thanks!
