### ISSUE TITLE
Help find you pkg

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-match-helper#6]
@phloe Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by phloe** [comment]
It was actually added to a list in posthml docs a while back: https://github.com/posthtml/posthtml/commit/c2fc65207529abfb1f712eb5e3132cd59ed6fd74

I didn't think it was a plugin as such - more a utility/helper function... but if it fits in your definition of plugin I have no objections :)

I'm willing to move the repo to the posthtml org - no problem :)

**Comment by Scrum** [comment]
> It was actually added to a list in posthml docs a while back: https://github.com/posthtml/posthtml/commit/c2fc65207529abfb1f712eb5e3132cd59ed6fd74
> 
> 
> 
> I didn't think it was a plugin as such - more a utility/helper function... but if it fits in your definition of plugin I have no objections :)
> 
> 
> 
> I'm willing to move the repo to the posthtml org - no problem :)


for this it is necessary that I have rights like ‘owner’ or do a plug-in transfer to my account

**Comment by Scrum** [comment]
I received an [invitation](https://github.com/phloe/posthtml-match-helper/invitations) to collaborate, but unfortunately this is not enough to have access to the movement, it requires rights owner

**Comment by phloe** [comment]
Hmmm, I was assuming I would get more options to grant additional access right once you were added as a collaborator. I don't see how I can add you as an "owner" as is... without straight out transferring the repo to you.

**Comment by Scrum** [comment]
@phloe welcome aboard, check access rights

**Comment by phloe** [comment]
Looks good :)
