### ISSUE TITLE
Does not work with className of `fade:not(.show)`

### ISSUE THREAD

**Issue by titanism** [posthtml/posthtml-match-helper#8]
If you have a `className` value of `fade:not(.show)` it will result in this error:

```sh
SyntaxError: Invalid regular expression: /(?:^|\s)fade:not(\s(?:.*?\s)?show)(?:\s|$)|(?:^|\s)show)\s(?:.*?\s)?fade:not((?:\s|$)/: Unmatched ')'
    at new RegExp (<anonymous>)
    at expandMatcher (/Users/user/Projects/email-templates/node_modules/.pnpm/posthtml-match-helper@1.0.3_posthtml@0.16.6/node_modules/posthtml-match-helper/index.js:37:28)
    at module.exports (/Users/user/Projects/email-templates/node_modules/.pnpm/posthtml-match-helper@1.0.3_posthtml@0.16.6/node_modules/posthtml-match-helper/index.js:144:11)
    at /Users/user/Projects/email-templates/node_modules/.pnpm/posthtml-inline-css@1.2.3_posthtml@0.16.6/node_modules/posthtml-inline-css/lib/inlineCss.js:30:62
    at Array.forEach (<anonymous>)
    at /Users/user/Projects/email-templates/node_modules/.pnpm/posthtml-inline-css@1.2.3_posthtml@0.16.6/node_modules/posthtml-inline-css/lib/inlineCss.js:29:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
```

**Comment by phloe** [comment]
Hmmm... It's not ideal that the match helper function throws like that - I agree - but you're feeding it a pseudo selector (i.e. `:not()`) which is not currently supported:

<img width="839" alt="Screenshot 2023-02-10 at 00 17 31" src="https://user-images.githubusercontent.com/13237/217962426-0a81b40d-aae8-4a1f-a631-9ce2a498be40.png">

The proposed fix would just make the match helper fail silently? - or not return the correct nodes?

**Comment by phloe** [comment]
Please read the documentation for supported features: https://github.com/posthtml/posthtml-match-helper

Only a subset of CSS selectors are supported.

**Comment by phloe** [comment]
I think the best strategy would be for posthtml-inline-css to strip pseudo selectors before handing them to the match helper - or wrap the block where it's used in try/catch.

Just wrapping in try/catch will mean selectors that _would_ matched are left out of the inlined css - negating what you are trying to achieve by inlining :(

Of course adding proper support for `:not()` (and maybe other pseudo selectors) might be doable - but would require some work.
